dataset: cifar100
num_classes: 100
device: "0"
teacher_ckpt: /home/user1/kd/classification/teachers/swin_tiny_patch4_window7_224_cifar100.pth

student_is_cnn: true
cross_head: 4
assist_kd: kd
#mlkd
mlkd_ce: 1
mlkd_kd: 1

#dkd
dkd_alpha: 1
dkd_beta: 8

#dist
dist_beta: 1
dist_gamma: 1

reprob: 0.25
aa: null
batch_size: 64
schedule: [150,180,210] 
color_jitter: 0.0
cutout_length: 0
decay_by_epoch: True
decay_epochs: 100
decay_rate: 0.1
drop: 0.0
epochs: 240
log_interval: 200
lr: 0.05 
smoothing: 0.1 
min_lr: 1.0e-6 
model_ema: false
model_ema_decay: 0.9998
momentum: 0.9
opt: sgd
opt_betas: null
opt_eps: 1.0e-08
remode: const 
sched: step 
seed: 42
warmup_epochs: 0 
warmup_lr: 1.0e-6 
weight_decay: 5.0e-4
workers: 4
sgd_no_nesterov: True
opt_no_filter: True
experiment: Swint-resnet18
# kd
ori_loss_weight:  1.
kd_loss_weight: 1.
kd: diffkd
teacher_model: timm_swin_tiny_patch4_window7_224
model: timm_resnet18
teacher_pretrained: False
kd_loss_kwargs:
  use_ae: True
  ae_channels: 1024
  tau: 4
